# -*- coding: utf-8 -*-
"""wad_tools.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8___khY3vVKn7eCK7h5i1uGTHVt175O
"""

"""
Mask R-CNN
Train on the dataset for Kaggle's WAD competition.

Reem Al-Halimi
------------------------------------------------------------

Based on Waleed Abdulla's balloon Mask R-CNN sample scripts.

Copyright (c) 2018 Matterport, Inc.
Licensed under the MIT License (see LICENSE for details)
Written by Waleed Abdulla

------------------------------------------------------------

Usage: import the module (see Jupyter notebooks for examples), or run from
       the command line as such:

    # Train a new model starting from pre-trained COCO weights
    python3 wad_tools.py train --labels_file=/home/paperspace/data/wad/wad_labels.csv --dataset=/home/paperspace/data/wad --weights=coco
    python3 wad_tools.py train --labels_file=/path/to/WAD/wad_labels.csv --dataset=/path/to/WAD/dataset --weights=coco

    # Resume training a model that you had trained earlier
    python3 wad_tools.py train --dataset=/path/to/WAD/dataset --weights=last

    # Train a new model starting from ImageNet weights
    python3 wad_tools.py train --dataset=/path/to/WAD/dataset --weights=imagenet

    # Apply color splash to an image
    python3 wad_tools.py splash --weights=/path/to/WAD/file.h5 --image=<URL or path to file>

    # Apply color splash to video using the last weights you trained
    python3 wad_tools.py splash --weights=last --video=<URL or path to file>
"""
import os
import sys
home_dir="/home/paperspace/"
module_path = (os.path.join(home_dir+'Mask_RCNN-master/'),
               os.path.join(home_dir+'cocoapi/PythonAPI/'), 
               os.path.join(home_dir+'cocoapi/PythonAPI/pycocotools/'), 
               os.path.join(home_dir+'Mask_RCNN-master/samples/driving'))
for p in module_path:
  if p not in sys.path:
    sys.path.append(p)
    
import json
import random
import datetime
import numpy as np
import cv2
import skimage.draw
from sklearn.model_selection import train_test_split
from tqdm import *
import math
import pandas as pd

# Root directory of the project
ROOT_DIR = os.getcwd()
if ROOT_DIR.endswith("samples/wad"):
    # Go up two levels to the repo root
    ROOT_DIR = os.path.dirname(os.path.dirname(ROOT_DIR))

# Import Mask RCNN
sys.path.append(ROOT_DIR)
from config import Config
import utils
import model as modellib

# Path to trained weights file
COCO_WEIGHTS_PATH = os.path.join(ROOT_DIR, "mask_rcnn_coco.h5")

# Directory to save logs and model checkpoints, if not provided
# through the command line argument --logs
DEFAULT_LOGS_DIR = os.path.join(ROOT_DIR, "logs")

############################################################
#  Configurations
############################################################


class WADConfig(Config):
    """Configuration for training on the toy  dataset.
    Derives from the base Config class and overrides some values.
    """
    # Give the configuration a recognizable name
    NAME = "WAD"

    # We use a GPU with 12GB memory, which can fit two images.
    # Adjust down if you use a smaller GPU.
    IMAGES_PER_GPU = 1

    # Number of classes (including background)
    NUM_CLASSES = 1 + 36  # Background + 36 categories for WAD dataset

    # Number of training steps per epoch
    STEPS_PER_EPOCH = 100

    # Skip detections with < 90% confidence
    DETECTION_MIN_CONFIDENCE = 0.9

    # Input image resing
    # Images are resized such that the smallest side is >= IMAGE_MIN_DIM and
    # the longest side is <= IMAGE_MAX_DIM. In case both conditions can't
    # be satisfied together the IMAGE_MAX_DIM is enforced.
    IMAGE_MIN_DIM = 800
    IMAGE_MAX_DIM = 1024
    
    #Which classes to ignore
    # ignore 'others', 'unlabeled', and 'BG'
    IGNORE_CATS_LIST = [0,255]
    
    # name of image and label subdirectories for each dataset segment
    DATASET_DICT= {"train":{"images": "train_color", "labels":"train_label"}, 
                "test":{"images":"test", "labels":None}}
    
    # The desired maximum number of images to use from the dataset.
    # set to None or <= 0 to use the whole dataset
    MAX_DATASET_SIZE = 500

############################################################
#  Dataset
############################################################

class WADDataset(utils.Dataset):

  def __init__(self, labels_file, dataset_dict, ignore_cats=[],  *args, **kwargs):
      """labels_file: A csv file containing the list of labels and their WAD ID delimited by a comma
                      with a header as the first line.
         dataset_dict: a dictionary with the name of the images and labels (annotation) subdirectories
                       for each dataset segment (train, test, etc.)
         ignore_cats: a list of WAD category ids to ignore.
      """
      super(WADDataset, self).__init__(*args, **kwargs)
      self.ignore_cats= ignore_cats
      self.dataset_dict = dataset_dict
      self._getClasses(labels_file)
      self.class_from_source_map = self._createClassIndex()
      
    
  def _createClassIndex(self):
      """map the index i in class_info to the class id in class_info[i]["id"]
         so that self.classIndex(id) returns the index i where class_info[i]["id"]=id
      """
      classIndex = {}
      for i, info in enumerate(self.class_info): 
          classIndex[str(info["source"])+"."+str(info["id"])]= int(i)
      return classIndex
        
  def _getClasses(self, labels_file):
        labels = pd.read_csv(labels_file)
        for index, row in labels.iterrows():
            self.add_class("WAD", int(row['id']), row['cat'])


  def _adjust_gamma(self, image, gamma=1.0):
        # build a lookup table mapping the pixel values [0, 255] to
        # their adjusted gamma values
        # Source: https://www.pyimagesearch.com/2015/10/05/opencv-gamma-correction/

        invGamma = 1.0 / gamma
        table = np.array([((i / 255.0) ** invGamma) * 255
          for i in np.arange(0, 256)]).astype("uint8")

        # apply gamma correction using the lookup table
        return cv2.LUT(image, table)

  def load_image(self, image_id, image_path=None, gamma=2.0): #, img_h, img_w, img_ch, resize_mode='constant'):
        """Load the specified image and return a [H,W,3] Numpy array.
        """
        if image_path == None:
              image_path = os.path.join(self.image_info[image_id]["path"], 
                                        self.dataset_dict[self.image_info[image_id]["image_subset"]]["images"],
                                        str(self.image_info[image_id]["id"])+'.jpg')
        # Load image
        image = skimage.io.imread(image_path)
        img_shape = [image.shape[0], image.shape[1]]
        #img = resize(img, (img_h, img_w), mode=resize_mode, preserve_range=True)
        # If grayscale. Convert to RGB for consistency.
        if image.ndim != 3:
            image = skimage.color.gray2rgb(image)
        elif (len(image.shape)==3) and (image.shape[2]==4):
            image = cv2.cvtColor(image, cv2.COLOR_RGBA2RGB) #skimage.color.rgba2rgb(image) #remove the alpha channel
            image = self._adjust_gamma(image, gamma)

        image = np.array(image, dtype=np.uint8)

        return image

  def load_wad(self, root_dataset_dir, subset="train", image_ids=None, num_images=None):
        """Load a subset of the WAD dataset.
        dataset_dir: Root directory of the dataset.
        subset: Subset to load: train or val
        image_ids: images to be retrieved from the given directory
        num_images: the number of images to be retrieved. If not given, all images are returned
        """
        # Add classes. 
        self.add_class("WAD", 1, "WAD")

        # Train or validation dataset?
        assert subset in ["train", "test", "test2"]
        assert ((num_images is None) or (num_images >0))
        dataset_dir = os.path.join(root_dataset_dir, self.dataset_dict[subset]["images"])

        # Add images
        # Get train and test IDs
        if image_ids is None:
            # Get all the files in the subset and remove their exntension to generate the image_ids
            image_ids = [os.path.splitext(f)[0] for f in os.listdir(dataset_dir) if os.path.isfile(os.path.join(dataset_dir, f))]
        if not(image_ids is None) and (len(image_ids)>0):
            if not(num_images is None):
                image_ids = image_ids[0:min(num_images, len(image_ids))]
            for id_ in tqdm(image_ids, total=len(image_ids), unit="images"):
                image_path = dataset_dir # image path is the directory containing the image and its masks
                full_path = os.path.join(image_path, id_+'.jpg')
                image = self.load_image(id_, image_path=full_path)
                height= image.shape[0]
                width = image.shape[1]

                self.add_image(
                    "WAD",
                    image_subset= subset,
                    image_id=id_,  # use directory name (i.e. image name without teh .png extension) as a unique image id
                    path=root_dataset_dir, # image path is the directory comtaining the image and its masks
                    width=width, height=height)
        else:
            print("No images found in", dataset_dir)

  def load_mask(self, image_id):
        """Generate instance masks for an image.
        Returns:
          masks: A bool array of shape [height, width, instance count] with
              one mask per instance.
          class_ids: a 1D array of class IDs of the instance masks.
        """
        # If not a WAD dataset image, delegate to parent class.
        image_info = self.image_info[image_id]
        if image_info["source"] != "WAD":
            return super(self.__class__, self).load_mask(image_id)

        info = self.image_info[image_id]
        # Read the image labels array
        mask_path = os.path.join(info["path"], 
                                 self.dataset_dict[info["image_subset"]]["labels"])
        compound_mask = np.array(skimage.io.imread(os.path.join(mask_path, 
                                                                str(info["id"]) +"_instanceIds.png")), dtype=np.uint16)
        height = compound_mask[0]
        width = compound_mask[1]
        cats= (compound_mask//1000).astype(np.uint32)
        instances= (compound_mask%1000)+1
        cat_list= []
        mask=[]
        num_masks=-1
        cats_to_use= list(set(np.unique(cats))-set(self.ignore_cats))
        for cat in cats_to_use:
            cat_mask = cats.copy()
            # remove other cat masks
            cat_mask[cat_mask!=cat]= 0
            cat_instances = instances.copy()
            # remove other cats' instances
            cat_instances[cat_mask==0]=0
            for instance in np.unique(cat_instances):
                num_masks +=1
                tmp = cat_instances.copy()
                tmp[cat_instances!=instance] = 0
                tmp[cat_instances>instance] = 255
                mask.append(tmp)
                cat_list.append(int(self.map_source_class_id(info["source"]+"."+str(cat))))
        
        mask = np.moveaxis(np.array(mask,dtype=np.uint8), 0, -1)
        
        # Return mask, and array of class IDs of each instance. 
        return mask , np.array(cat_list, dtype=np.int32)

  def image_reference(self, image_id):
        """Return the path of the image."""
        info = self.image_info[image_id]
        if info["source"] == "WAD":
            return info["path"]
        else:
            super(self.__class__, self).image_reference(image_id)

def train(model, config):
    """Train the model."""

    try: config.MAX_DATASET_SIZE
    except NameError: config.MAX_DATASET_SIZE = None
        
    # Get the list of image IDs
    dataset_dir = os.path.join(args.dataset, config.DATASET_DICT["train"]["images"])
    image_ids = [os.path.splitext(f)[0] for f in os.listdir(dataset_dir) if os.path.isfile(os.path.join(dataset_dir, f))]
    
    #get a subset of the image_ids if the configured maximum is less than the number of available ids
    if (not(config.MAX_DATASET_SIZE is None) and (config.MAX_DATASET_SIZE>0)) \
       and (len(image_ids) > config.MAX_DATASET_SIZE):
        image_ids = random.sample(image_ids, config.MAX_DATASET_SIZE)
        
    if not(args.val_size is None) and (args.val_size > 0):
        val_size = args.val_size
        if (val_size).is_integer():
            val_size = int(val_size)
    else:
        val_size = 0.25

    if not(args.lr is None) and (args.lr > 0):
        learning_rate = args.lr
    else:
        learning_rate = config.LEARNING_RATE

    if not(args.train_size is None) and (args.train_size > 0):
        if (args.train_size).is_integer():
            train_size = int(args.train_size)
        else:
            train_size = args.train_size
        #split ids into training and validation sets
        train_image_ids, val_image_ids = train_test_split(image_ids, shuffle=True, train_size=train_size, test_size=val_size)
    else:
        #split ids into training and validation sets
        train_image_ids, val_image_ids = train_test_split(image_ids, shuffle=True, test_size=val_size)


    # Training dataset.
    print("Creating training set..")
    print("dataset dict:", config.DATASET_DICT)
    print("Ignore list: ", config.IGNORE_CATS_LIST)
    print("labels file: ", args.labels_file)
    dataset_train = WADDataset(args.labels_file, config.DATASET_DICT, ignore_cats=config.IGNORE_CATS_LIST)
    dataset_train.load_wad(args.dataset, "train", image_ids= train_image_ids)
    dataset_train.prepare()

    # Validation dataset (the images to be used for validation are under the same dir as the training images)
    print("Creating validation set..")
    dataset_val = WADDataset(args.labels_file, config.DATASET_DICT, ignore_cats=config.IGNORE_CATS_LIST)
    dataset_val.load_wad(args.dataset, "train", val_image_ids)
    dataset_val.prepare()

    # *** This training schedule is an example. Update to your needs ***
    # Since we're using a very small dataset, and starting from
    # COCO trained weights, we don't need to train too long. Also,
    # no need to train all layers, just the heads should do it.
    print("Training network heads")
    model.train(dataset_train, dataset_val,
                learning_rate=learning_rate,
                epochs=args.epochs,
                layers=args.layers)


def color_splash(image, mask):
    """Apply color splash effect.
    image: RGB image [height, width, 3]
    mask: instance segmentation mask [height, width, instance count]

    Returns result image.
    """
    # Make a grayscale copy of the image. The grayscale copy still
    # has 3 RGB channels, though.
    gray = skimage.color.gray2rgb(skimage.color.rgb2gray(image)) * 255
    # We're treating all instances as one, so collapse the mask into one layer
    mask = (np.sum(mask, -1, keepdims=True) >= 1)
    # Copy color pixels from the original color image where mask is set
    if mask.shape[0] > 0:
        splash = np.where(mask, image, gray).astype(np.uint8)
    else:
        splash = gray
    return splash


def detect_and_color_splash(model, image_path=None, video_path=None):
    assert image_path or video_path

    # Image or video?
    if image_path:
        # Run model detection and generate the color splash effect
        print("Running on {}".format(args.image))
        # Read image
        image = skimage.io.imread(args.image)
        # Detect objects
        r = model.detect([image], verbose=1)[0]
        # Color splash
        splash = color_splash(image, r['masks'])
        # Save output
        file_name = "splash_{:%Y%m%dT%H%M%S}.png".format(datetime.datetime.now())
        skimage.io.imsave(file_name, splash)
    elif video_path:
        import cv2
        # Video capture
        vcapture = cv2.VideoCapture(video_path)
        width = int(vcapture.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(vcapture.get(cv2.CAP_PROP_FRAME_HEIGHT))
        fps = vcapture.get(cv2.CAP_PROP_FPS)

        # Define codec and create video writer
        file_name = "splash_{:%Y%m%dT%H%M%S}.avi".format(datetime.datetime.now())
        vwriter = cv2.VideoWriter(file_name,
                                  cv2.VideoWriter_fourcc(*'MJPG'),
                                  fps, (width, height))

        count = 0
        success = True
        while success:
            print("frame: ", count)
            # Read next image
            success, image = vcapture.read()
            if success:
                # OpenCV returns images as BGR, convert to RGB
                image = image[..., ::-1]
                # Detect objects
                r = model.detect([image], verbose=0)[0]
                # Color splash
                splash = color_splash(image, r['masks'])
                # RGB -> BGR to save image to video
                splash = splash[..., ::-1]
                # Add image to video writer
                vwriter.write(splash)
                count += 1
        vwriter.release()
    print("Saved to ", file_name)

############################################################
#  Training
############################################################

if __name__ == '__main__':
    import argparse

    # Parse command line arguments
    parser = argparse.ArgumentParser(
        description='Train Mask R-CNN to detect objects in streetscape video frames.')
    parser.add_argument("command",
                        metavar="<command>",
                        help="'train' or 'splash'")
    parser.add_argument('--dataset', required=False,
                        metavar="/path/to/WAD/dataset/",
                        help='Directory of the WAD dataset')
    parser.add_argument('--labels_file', required=False,
                        metavar="/path/to/labels/file/",
                        help='CSV file containing labels and their ids')
    parser.add_argument('--weights', required=True,
                        metavar="/path/to/weights.h5",
                        help="Path to weights .h5 file or 'coco'")
    parser.add_argument('--logs', required=False,
                        default=DEFAULT_LOGS_DIR,
                        metavar="/path/to/logs/",
                        help='Logs and checkpoints directory (default=logs/)')
    parser.add_argument('--image', required=False,
                        metavar="path or URL to image",
                        help='Image to apply the color splash effect on')
    parser.add_argument('--video', required=False,
                        metavar="path or URL to video",
                        help='Video to apply the color splash effect on')
    parser.add_argument('--train_size', required=False, type=float,
                        metavar="the size of the training set",
                        help='the size of the training set')
    parser.add_argument('--val_size', required=False, type=float, default=0.25,
                        metavar="the size of the validation set",
                        help='the size of the validation set (default is 0.25)')
    parser.add_argument('--epochs', required=False, type=float, default=10,
                        metavar="the number of epochs",
                        help='the number of training epochs (default is 10)')
    parser.add_argument('--lr', required=False, type=float,
                        metavar="learning rate",
                        help='learning rate in training(default is LEARNING_RATE as defind in config.py)')
    parser.add_argument('--layers', required=False, default='heads',
                        metavar = "Which parts of the network to train: heads (for all but the backbone), 3+/4+/5+ (for the specific Resnet stage to train), or all (for all layers)")
    args = parser.parse_args()

    # Validate arguments
    if args.command == "train":
        assert args.dataset, "Argument --dataset is required for training"
    elif args.command == "splash":
        assert args.image or args.video,\
               "Provide --image or --video to apply color splash"

    print("Weights: ", args.weights)
    print("Dataset: ", args.dataset)
    print("Logs: ", args.logs)

    # Configurations
    if args.command == "train":
        config = WADConfig()
    else:
        class InferenceConfig(WADConfig):
            # Set batch size to 1 since we'll be running inference on
            # one image at a time. Batch size = GPU_COUNT * IMAGES_PER_GPU
            GPU_COUNT = 1
            IMAGES_PER_GPU = 1
        config = InferenceConfig()
    config.display()

    # Create model
    if args.command == "train":
        model = modellib.MaskRCNN(mode="training", config=config,
                                  model_dir=args.logs)
    else:
        model = modellib.MaskRCNN(mode="inference", config=config,
                                  model_dir=args.logs)

    # Select weights file to load
    if args.weights.lower() == "coco":
        weights_path = COCO_WEIGHTS_PATH
        # Download weights file
        if not os.path.exists(weights_path):
            utils.download_trained_weights(weights_path)
    elif args.weights.lower() == "last":
        # Find last trained weights
        weights_path = model.find_last()[1]
    elif args.weights.lower() == "imagenet":
        # Start from ImageNet trained weights
        weights_path = model.get_imagenet_weights()
    else:
        weights_path = args.weights

    # Load weights
    print("Loading weights ", weights_path)
    if args.weights.lower() == "coco":
        # Exclude the last layers because they require a matching
        # number of classes
        model.load_weights(weights_path, by_name=True, exclude=[
            "mrcnn_class_logits", "mrcnn_bbox_fc",
            "mrcnn_bbox", "mrcnn_mask"])
    else:
        model.load_weights(weights_path, by_name=True)

    # Train or evaluate
    if args.command == "train":
        print("setting up for training...")
        train(model, config)
    elif args.command == "splash":
        print("Splashing...")
        detect_and_color_splash(model, image_path=args.image,
                                video_path=args.video)
    else:
        print("'{}' is not recognized. "
              "Use 'train' or 'splash'".format(args.command))
